/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as MyListingsRouteImport } from './routes/my-listings'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AddPropertyRouteImport } from './routes/add-property'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PropertyIdRouteImport } from './routes/property.$id'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const MyListingsRoute = MyListingsRouteImport.update({
  id: '/my-listings',
  path: '/my-listings',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AddPropertyRoute = AddPropertyRouteImport.update({
  id: '/add-property',
  path: '/add-property',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyIdRoute = PropertyIdRouteImport.update({
  id: '/property/$id',
  path: '/property/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/add-property': typeof AddPropertyRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/compare': typeof CompareRoute
  '/favorites': typeof FavoritesRoute
  '/messages': typeof MessagesRoute
  '/my-listings': typeof MyListingsRoute
  '/search': typeof SearchRoute
  '/property/$id': typeof PropertyIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/add-property': typeof AddPropertyRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/compare': typeof CompareRoute
  '/favorites': typeof FavoritesRoute
  '/messages': typeof MessagesRoute
  '/my-listings': typeof MyListingsRoute
  '/search': typeof SearchRoute
  '/property/$id': typeof PropertyIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/add-property': typeof AddPropertyRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/compare': typeof CompareRoute
  '/favorites': typeof FavoritesRoute
  '/messages': typeof MessagesRoute
  '/my-listings': typeof MyListingsRoute
  '/search': typeof SearchRoute
  '/property/$id': typeof PropertyIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/add-property'
    | '/admin'
    | '/auth'
    | '/compare'
    | '/favorites'
    | '/messages'
    | '/my-listings'
    | '/search'
    | '/property/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/add-property'
    | '/admin'
    | '/auth'
    | '/compare'
    | '/favorites'
    | '/messages'
    | '/my-listings'
    | '/search'
    | '/property/$id'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/add-property'
    | '/admin'
    | '/auth'
    | '/compare'
    | '/favorites'
    | '/messages'
    | '/my-listings'
    | '/search'
    | '/property/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AddPropertyRoute: typeof AddPropertyRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  CompareRoute: typeof CompareRoute
  FavoritesRoute: typeof FavoritesRoute
  MessagesRoute: typeof MessagesRoute
  MyListingsRoute: typeof MyListingsRoute
  SearchRoute: typeof SearchRoute
  PropertyIdRoute: typeof PropertyIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AddPropertyRoute: AddPropertyRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  CompareRoute: CompareRoute,
  FavoritesRoute: FavoritesRoute,
  MessagesRoute: MessagesRoute,
  MyListingsRoute: MyListingsRoute,
  SearchRoute: SearchRoute,
  PropertyIdRoute: PropertyIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
